version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example

  studio:
    build: .
    ports:
      - "5555:5555"
    command: npx prisma studio
    depends_on:
      - app
    volumes:
      - .:/app
      - ./.env:/app/.env